### ISSUE TITLE
测试集的准确率要怎么修改代码吗？

### ISSUE THREAD

**Issue by FrankYogan** [mountainguan/fastText_learning#2]
您好 请问加载模型之后预测测试集的准确率要怎么修改代码吗？
print("准确率：", result.precision)
提示
AttributeError: 'tuple' object has no attribute 'precision'

**Comment by mountainguan** [comment]
没有记录fastText的版本号，api的变更较大，这边也找不到，fasttext本来也不需要什么知识，只要看看api就能写出demo。可以利用我这里的数据重新做一个demo
