### ISSUE TITLE
AttributeError: module 'fasttext' has no attribute 'train_supervised'

### ISSUE THREAD

**Issue by loveJasmine** [mountainguan/fastText_learning#3]
Building prefix dict from the default dictionary ...
Loading model from cache C:\Temp\jieba.cache
Loading model cost 0.968 seconds.
Prefix dict has been built succesfully.
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    classifier = fasttext.train_supervised("data/trained.txt",epoch=10,ws=2 , lr=0.5, wordNgrams=1, dim=1000,label=u"__label__",loss=u'softmax')
AttributeError: module 'fasttext' has no attribute 'train_supervised'

**Comment by mountainguan** [comment]
api变了，这里的代码一年多了。自行查一下api吧
